openapi: 3.0.0
info:
  title: Product Comments API
  version: 1.0.0
  description: API for managing comments on products.
servers:
  - url: http://localhost:3000/api
paths:
  /products/{id}/comments:
    get:
      summary: Retrieve comments for a product
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the product to retrieve comments for
          schema:
            type: string
      responses:
        '200':
          description: A list of comments for the product
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    userId:
                      type: string
                    productId:
                      type: string
                    comment:
                      type: string
        '404':
          description: Product not found
        '500':
          description: Internal Server Error

    post:
      summary: Create a new comment for a product
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the product to add a comment to
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                productId:
                  type: string
                comment:
                  type: string
              required:
                - userId
                - comment
      responses:
        '201':
          description: Comment created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  product:
                    type: object
                    properties:
                      comments:
                        type: array
                        items:
                          type: object
                          properties:
                            userId:
                              type: string
                            productId:
                              type: string
                            comment:
                              type: string
        '404':
          description: Product not found
        '500':
          description: Internal Server Error
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
