openapi: 3.0.0
info:
  title: User Authentication API
  version: 1.0.0
  description: API for user authentication including login functionality.
paths:
  /api/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  description: The email of the user
                  example: user@example.com
                password:
                  type: string
                  description: The password of the user
                  example: password123
              required:
                - email
                - password
      responses:
        200:
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT token for authentication
                  userId:
                    type: string
                    description: The ID of the logged-in user
                  username:
                    type: string
                    description: The username of the logged-in user
                required:
                  - token
                  - userId
                  - username
        400:
          description: Invalid email or password
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message
                    example: Invalid email or password
        500:
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message
