openapi: 3.0.0
info:
  title: User Authentication API
  version: 1.0.0
  description: API for user authentication, including signup functionality.
paths:
  /api/signup:
    post:
      summary: User registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: The username of the user
                  example: newuser
                email:
                  type: string
                  format: email
                  description: The email of the user
                  example: user@example.com
                password:
                  type: string
                  description: The password of the user
                  example: password123
              required:
                - username
                - email
                - password
      responses:
        201:
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT token for authentication
                  userId:
                    type: string
                    description: The ID of the newly created user
                  username:
                    type: string
                    description: The username of the newly created user
                required:
                  - token
                  - userId
                  - username
        400:
          description: User already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message
                    example: User already exists
        500:
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message
